@echo off
setlocal EnableDelayedExpansion
cd /d "%~dp0"

rem ============================================================
rem  Project Setup  [self-unpacking]
rem  Generated by Venv Batch Template Generator (Leon Priest / 7h3v01d) v3.4.0
rem  Generated on: 2026-06-23 16:26
rem
rem  Ship ONLY this file in your repo.  On first run it:
rem    1. Checks Python
rem    2. Creates / verifies the virtual environment
rem    3. Installs dependencies
rem    4. Writes companion scripts beside this file:
rem       run.bat  pip.bat  shell.bat  sync.bat  doctor.bat  test.bat
rem
rem  Companion scripts are NOT overwritten if they already exist.
rem  Add them to .gitignore to keep your repo tidy.
rem ============================================================

set "PROJECT_NAME=TimeCraft"
set "VENV_DIR=.venv"

title "%PROJECT_NAME% - SETUP"

echo ============================================================
echo  Setup: %PROJECT_NAME%
echo ============================================================
echo.

rem ── 1. Environment check + venv bootstrap ───────────────────
where python >nul 2>&1
if errorlevel 1 (
    echo [ERROR] Python is not installed or not on PATH.
    echo.
    echo Install Python from https://www.python.org/downloads/
    echo Make sure to check "Add Python to PATH" during installation.
    echo.
    pause
    exit /b 1
)

if exist "%VENV_DIR%\Scripts\python.exe" (
    echo [INFO] Virtual environment already exists at "%VENV_DIR%\"
    echo        Skipping creation.
    echo.
) else (
    echo [1/3] Creating virtual environment...
    echo ============================================================
    python -m venv "%VENV_DIR%"
    if errorlevel 1 ( echo [ERROR] venv creation failed. & pause & exit /b 1 )
    echo.

    echo [2/3] Upgrading pip...
    echo ============================================================
    "%VENV_DIR%\Scripts\python.exe" -m pip install --upgrade pip
    echo.

    if exist "requirements.txt" (
        echo [3/3] Installing dependencies from requirements.txt...
        echo ============================================================
        "%VENV_DIR%\Scripts\python.exe" -m pip install -r requirements.txt
        echo.
    ) else (
        echo [3/3] SKIPPED: No requirements.txt found.
        echo        Run sync.bat after adding dependencies.
        echo.
    )
)

rem ── 2. Write companion scripts ───────────────────────────────
echo ============================================================
echo  Writing companion scripts...
echo ============================================================
echo.

rem ── run.bat ─────────────────────────────────────────────────
set "OUTFILE=run.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_run_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpzZXRsb2NhbCBFbmFibGVEZWxheWVkRXhwYW5zaW9uDQpjZCAvZCAiJX5kcDAi
        echo DQoNCnJlbSA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT0NCnJlbSAgUHJvamVjdCBSdW5uZXINCnJlbSAgR2VuZXJhdGVkIGJ5IFZlbnYg
        echo QmF0Y2ggVGVtcGxhdGUgR2VuZXJhdG9yIChMZW9uIFByaWVzdCAvIDdoM3YwMWQpIHYzLjQuMA0K
        echo cmVtICBHZW5lcmF0ZWQgb246IDIwMjYtMDYtMjMgMTY6MjYNCnJlbQ0KcmVtICBFTlRSWV9NT0RF
        echo Og0KcmVtICAgIGZpbGUgICAtPiBweXRob24gYXBwLnB5DQpyZW0gICAgbW9kdWxlIC0+IHB5dGhv
        echo biAtbSBwYWNrYWdlLm1vZHVsZQ0KcmVtICAgIHJ1bm5lciAtPiBweXRob24gLW0gcnVubmVyX21v
        echo ZHVsZSBbYXJncy4uLl0NCnJlbSA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT0NCg0Kc2V0ICJQUk9KRUNUX05BTUU9VGltZUNyYWZ0Ig0K
        echo c2V0ICJWRU5WX0RJUj0udmVudiINCnNldCAiRU5UUllfTU9ERT1maWxlIg0Kc2V0ICJBUFBfRU5U
        echo Ulk9dGltZWNyYWZ0XG1haW4ucHkiDQpzZXQgIlJVTk5FUl9BUkdTPSINCg0Kc2V0ICJQWT0lQ0Ql
        echo XCVWRU5WX0RJUiVcU2NyaXB0c1xweXRob24uZXhlIg0KDQppZiBub3QgZXhpc3QgIiVQWSUiICgN
        echo CiAgICBlY2hvIFtFUlJPUl0gTG9jYWwgdmVudiBub3QgZm91bmQ6ICIlUFklIg0KICAgIGVjaG8u
        echo DQogICAgZWNobyBGaXggd2l0aDoNCiAgICBlY2hvICAgcHl0aG9uIC1tIHZlbnYgIiVWRU5WX0RJ
        echo UiUiDQogICAgZWNobyAgICIlVkVOVl9ESVIlXFNjcmlwdHNccHl0aG9uLmV4ZSIgLW0gcGlwIGlu
        echo c3RhbGwgLS11cGdyYWRlIHBpcA0KICAgIGVjaG8gICAiJVZFTlZfRElSJVxTY3JpcHRzXHB5dGhv
        echo bi5leGUiIC1tIHBpcCBpbnN0YWxsIC1yIHJlcXVpcmVtZW50cy50eHQNCiAgICBlY2hvLg0KICAg
        echo IHBhdXNlDQogICAgZXhpdCAvYiAxDQopDQoNCmlmIC9JICIlRU5UUllfTU9ERSUiPT0iZmlsZSIg
        echo aWYgbm90IGV4aXN0ICIlQVBQX0VOVFJZJSIgKA0KICAgIGVjaG8gW0VSUk9SXSBFbnRyeSBmaWxl
        echo IG5vdCBmb3VuZDogIiVBUFBfRU5UUlklIg0KICAgIGVjaG8gRWRpdCBydW4uYmF0IG9yIHJ1biB3
        echo aXRoIHRoZSBjb3JyZWN0IGVudHJ5IGZpbGUuDQogICAgcGF1c2UNCiAgICBleGl0IC9iIDENCikN
        echo Cg0KdGl0bGUgIiVQUk9KRUNUX05BTUUlIC0gUlVOIg0KZWNobyA9PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0NCmVjaG8gIFJ1bm5pbmcg
        echo OiAlUFJPSkVDVF9OQU1FJQ0KZWNobyAgUHJvamVjdCA6ICVDRCUNCmVjaG8gIFB5dGhvbiAgOiAl
        echo UFklDQplY2hvICBNb2RlICAgIDogJUVOVFJZX01PREUlDQplY2hvICBFbnRyeSAgIDogJUFQUF9F
        echo TlRSWSUNCmlmIC9JICIlRU5UUllfTU9ERSUiPT0icnVubmVyIiBlY2hvICBBcmdzICAgIDogJVJV
        echo Tk5FUl9BUkdTJQ0KZWNobyA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT0NCmVjaG8uDQoNCnNldCAiRVhJVENPREU9MCINCg0KaWYgL0kg
        echo IiVFTlRSWV9NT0RFJSI9PSJtb2R1bGUiICgNCiAgICAiJVBZJSIgLW0gJUFQUF9FTlRSWSUgJSoN
        echo CikgZWxzZSBpZiAvSSAiJUVOVFJZX01PREUlIj09InJ1bm5lciIgKA0KICAgIGlmIGRlZmluZWQg
        echo UlVOTkVSX0FSR1MgKA0KICAgICAgICAiJVBZJSIgLW0gJUFQUF9FTlRSWSUgIVJVTk5FUl9BUkdT
        echo ISAlKg0KICAgICkgZWxzZSAoDQogICAgICAgICIlUFklIiAtbSAlQVBQX0VOVFJZJSAlKg0KICAg
        echo ICkNCikgZWxzZSAoDQogICAgIiVQWSUiICIlQVBQX0VOVFJZJSIgJSoNCikNCg0Kc2V0ICJFWElU
        echo Q09ERT0hRVJST1JMRVZFTCEiDQoNCmVjaG8uDQplY2hvID09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQ0KZWNobyAgUHJvY2VzcyBleGl0
        echo ZWQgd2l0aCBjb2RlOiAhRVhJVENPREUhDQplY2hvID09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQ0KcGF1c2UNCmV4aXQgL2IgIUVYSVRD
        echo T0RFIQ0K
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

rem ── pip.bat ─────────────────────────────────────────────────
set "OUTFILE=pip.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_pip_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpzZXRsb2NhbA0KY2QgL2QgIiV+ZHAwIg0KDQpyZW0gPT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQpyZW0gIFByb2pl
        echo Y3QtbG9jYWwgcGlwIHdyYXBwZXINCnJlbSAgR2VuZXJhdGVkIGJ5IFZlbnYgQmF0Y2ggVGVtcGxh
        echo dGUgR2VuZXJhdG9yIChMZW9uIFByaWVzdCAvIDdoM3YwMWQpIHYzLjQuMA0KcmVtICBHZW5lcmF0
        echo ZWQgb246IDIwMjYtMDYtMjMgMTY6MjYNCnJlbQ0KcmVtICBVc2FnZToNCnJlbSAgICBwaXAuYmF0
        echo IGluc3RhbGwgcmVxdWVzdHMNCnJlbSAgICBwaXAuYmF0IGluc3RhbGwgLXIgcmVxdWlyZW1lbnRz
        echo LnR4dA0KcmVtICAgIHBpcC5iYXQgZnJlZXplID4gcmVxdWlyZW1lbnRzLnR4dA0KcmVtICAgIHBp
        echo cC5iYXQgbGlzdA0KcmVtICAgIHBpcC5iYXQgdW5pbnN0YWxsIHJlcXVlc3RzDQpyZW0gPT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQoN
        echo CnNldCAiVkVOVl9ESVI9LnZlbnYiDQpzZXQgIlBZPSVDRCVcJVZFTlZfRElSJVxTY3JpcHRzXHB5
        echo dGhvbi5leGUiDQoNCmlmIG5vdCBleGlzdCAiJVBZJSIgKA0KICAgIGVjaG8gW0VSUk9SXSBMb2Nh
        echo bCB2ZW52IHdhcyBub3QgZm91bmQ6DQogICAgZWNobyAgICAgICAgICIlUFklIg0KICAgIGVjaG8u
        echo DQogICAgZWNobyBDcmVhdGUgaXQgd2l0aDoNCiAgICBlY2hvICAgICAgICAgcHl0aG9uIC1tIHZl
        echo bnYgIiVWRU5WX0RJUiUiDQogICAgZWNoby4NCiAgICBwYXVzZQ0KICAgIGV4aXQgL2IgMQ0KKQ0K
        echo DQoiJVBZJSIgLW0gcGlwICUqDQpleGl0IC9iICVFUlJPUkxFVkVMJQ0K
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

rem ── shell.bat ─────────────────────────────────────────────────
set "OUTFILE=shell.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_shell_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpjZCAvZCAiJX5kcDAiDQoNCnJlbSA9PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0NCnJlbSAgUHJvamVjdCB2ZW52IHNo
        echo ZWxsDQpyZW0gIEdlbmVyYXRlZCBieSBWZW52IEJhdGNoIFRlbXBsYXRlIEdlbmVyYXRvciAoTGVv
        echo biBQcmllc3QgLyA3aDN2MDFkKSB2My40LjANCnJlbSAgR2VuZXJhdGVkIG9uOiAyMDI2LTA2LTIz
        echo IDE2OjI2DQpyZW0NCnJlbSAgT3BlbnMgYW4gYWN0aXZhdGVkIENNRCBzZXNzaW9uIGZvciB0aGlz
        echo IHByb2plY3QuDQpyZW0gIFVzZSBvbmx5IHdoZW4geW91IG5lZWQgYW4gaW50ZXJhY3RpdmUgdmVu
        echo diBzZXNzaW9uLg0KcmVtICBFeGl0IHdpdGg6IGV4aXQNCnJlbSA9PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0NCg0Kc2V0ICJQUk9KRUNU
        echo X05BTUU9VGltZUNyYWZ0Ig0Kc2V0ICJWRU5WX0RJUj0udmVudiINCnNldCAiQUNUSVZBVEU9JUNE
        echo JVwlVkVOVl9ESVIlXFNjcmlwdHNcYWN0aXZhdGUuYmF0Ig0KDQppZiBub3QgZXhpc3QgIiVBQ1RJ
        echo VkFURSUiICgNCiAgICBlY2hvIFtFUlJPUl0gTG9jYWwgdmVudiB3YXMgbm90IGZvdW5kOg0KICAg
        echo IGVjaG8gICAgICAgICAiJUFDVElWQVRFJSINCiAgICBlY2hvLg0KICAgIGVjaG8gQ3JlYXRlIGl0
        echo IHdpdGg6DQogICAgZWNobyAgICAgICAgIHB5dGhvbiAtbSB2ZW52ICIlVkVOVl9ESVIlIg0KICAg
        echo IGVjaG8uDQogICAgcGF1c2UNCiAgICBleGl0IC9iIDENCikNCg0KdGl0bGUgIiVQUk9KRUNUX05B
        echo TUUlIC0gVkVOViBTSEVMTCINCmNhbGwgIiVBQ1RJVkFURSUiDQoNCmVjaG8gPT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQplY2hvICBQ
        echo cm9qZWN0IHNoZWxsIGFjdGl2YXRlZA0KZWNobyAgUHJvamVjdDogIiVDRCUiDQplY2hvICBQeXRo
        echo b24gOg0Kd2hlcmUgcHl0aG9uDQplY2hvICBUeXBlICJleGl0IiB0byBsZWF2ZSB0aGlzIHNoZWxs
        echo Lg0KZWNobyA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT0NCmVjaG8uDQpjbWQgL2sNCg==
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

rem ── sync.bat ─────────────────────────────────────────────────
set "OUTFILE=sync.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_sync_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpzZXRsb2NhbA0KY2QgL2QgIiV+ZHAwIg0KDQpyZW0gPT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQpyZW0gIERlcGVu
        echo ZGVuY3kgU3luYyAocGlwKQ0KcmVtICBHZW5lcmF0ZWQgYnkgVmVudiBCYXRjaCBUZW1wbGF0ZSBH
        echo ZW5lcmF0b3IgKExlb24gUHJpZXN0IC8gN2gzdjAxZCkgdjMuNC4wDQpyZW0gIEdlbmVyYXRlZCBv
        echo bjogMjAyNi0wNi0yMyAxNjoyNg0KcmVtID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PQ0KDQpzZXQgIlBST0pFQ1RfTkFNRT1UaW1lQ3Jh
        echo ZnQiDQpzZXQgIlZFTlZfRElSPS52ZW52Ig0Kc2V0ICJQWT0lQ0QlXCVWRU5WX0RJUiVcU2NyaXB0
        echo c1xweXRob24uZXhlIg0KDQppZiBub3QgZXhpc3QgIiVQWSUiICgNCiAgICBlY2hvIFtFUlJPUl0g
        echo TG9jYWwgdmVudiBub3QgZm91bmQ6ICIlUFklIg0KICAgIGVjaG8uDQogICAgZWNobyBDcmVhdGUg
        echo aXQgd2l0aDoNCiAgICBlY2hvICAgcHl0aG9uIC1tIHZlbnYgIiVWRU5WX0RJUiUiDQogICAgcGF1
        echo c2UNCiAgICBleGl0IC9iIDENCikNCg0KdGl0bGUgIiVQUk9KRUNUX05BTUUlIC0gU1lOQyINCg0K
        echo ZWNobyA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT0NCmVjaG8gIFN5bmNpbmc6ICVQUk9KRUNUX05BTUUlDQplY2hvICBQeXRob24gOiAl
        echo UFklDQplY2hvID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PQ0KZWNoby4NCg0KZWNobyBbMS8zXSBVcGdyYWRpbmcgcGlwLi4uDQplY2hv
        echo ID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PQ0KIiVQWSUiIC1tIHBpcCBpbnN0YWxsIC0tdXBncmFkZSBwaXANCmVjaG8uDQoNCmlmIGV4
        echo aXN0ICJyZXF1aXJlbWVudHMudHh0IiAoDQogICAgZWNobyBbMi8zXSBJbnN0YWxsaW5nIGZyb20g
        echo cmVxdWlyZW1lbnRzLnR4dC4uLg0KICAgIGVjaG8gPT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQogICAgIiVQWSUiIC1tIHBpcCBpbnN0
        echo YWxsIC1yIHJlcXVpcmVtZW50cy50eHQNCiAgICBlY2hvLg0KKSBlbHNlICgNCiAgICBlY2hvIFsy
        echo LzNdIFNLSVBQRUQ6IE5vIHJlcXVpcmVtZW50cy50eHQgZm91bmQuDQogICAgZWNobyAgICAgICBD
        echo cmVhdGUgb25lIHdpdGg6IHBpcC5iYXQgZnJlZXplIF4+IHJlcXVpcmVtZW50cy50eHQNCiAgICBl
        echo Y2hvLg0KKQ0KDQplY2hvIFszLzNdIERlcGVuZGVuY3kgaGVhbHRoIGNoZWNrLi4uDQplY2hvID09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PQ0KIiVQWSUiIC1tIHBpcCBjaGVjaw0KZWNoby4NCg0KZWNobyA9PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0NCmVjaG8gIFNZTkMgQ09N
        echo UExFVEUNCmVjaG8gPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09DQpwYXVzZQ0KZXhpdCAvYiAwDQo=
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

rem ── doctor.bat ─────────────────────────────────────────────────
set "OUTFILE=doctor.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_doctor_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpzZXRsb2NhbA0KY2QgL2QgIiV+ZHAwIg0KDQpyZW0gPT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQpyZW0gIFByb2pl
        echo Y3QgRG9jdG9yDQpyZW0gIEdlbmVyYXRlZCBieSBWZW52IEJhdGNoIFRlbXBsYXRlIEdlbmVyYXRv
        echo ciAoTGVvbiBQcmllc3QgLyA3aDN2MDFkKSB2My40LjANCnJlbSAgR2VuZXJhdGVkIG9uOiAyMDI2
        echo LTA2LTIzIDE2OjI2DQpyZW0gPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09DQoNCnNldCAiUFJPSkVDVF9OQU1FPVRpbWVDcmFmdCINCnNl
        echo dCAiVkVOVl9ESVI9LnZlbnYiDQpzZXQgIkVOVFJZX01PREU9ZmlsZSINCnNldCAiQVBQX0VOVFJZ
        echo PXRpbWVjcmFmdFxtYWluLnB5Ig0Kc2V0ICJSVU5ORVJfQVJHUz0iDQpzZXQgIlBZPSVDRCVcJVZF
        echo TlZfRElSJVxTY3JpcHRzXHB5dGhvbi5leGUiDQoNCmVjaG8gPT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQplY2hvICBQUk9KRUNUIERP
        echo Q1RPUjogJVBST0pFQ1RfTkFNRSUNCmVjaG8gPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQplY2hvICBQcm9qZWN0IDogJUNEJQ0KZWNo
        echo byAgTW9kZSAgICA6ICVFTlRSWV9NT0RFJQ0KZWNobyAgRW50cnkgICA6ICVBUFBfRU5UUlklDQpp
        echo ZiAvSSAiJUVOVFJZX01PREUlIj09InJ1bm5lciIgZWNobyAgQXJncyAgICA6ICVSVU5ORVJfQVJH
        echo UyUNCmVjaG8uDQoNCmlmIG5vdCBleGlzdCAiJVBZJSIgKA0KICAgIGVjaG8gW0ZBSUxdIHZlbnYg
        echo bm90IGZvdW5kIGF0OiAiJVBZJSINCiAgICBlY2hvLg0KICAgIGVjaG8gQ3JlYXRlIGl0IHdpdGg6
        echo DQogICAgZWNobyAgIHB5dGhvbiAtbSB2ZW52ICIlVkVOVl9ESVIlIg0KICAgIHBhdXNlDQogICAg
        echo ZXhpdCAvYiAxDQopDQoNCmVjaG8gW09LXSB2ZW52IGZvdW5kOiAiJVBZJSINCmVjaG8uDQoNCmVj
        echo aG8gLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tDQplY2hvICBQeXRob24gRW52aXJvbm1lbnQNCmVjaG8gLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tDQoiJVBZJSIgLWMgImlt
        echo cG9ydCBzeXM7IHByaW50KCdFeGVjdXRhYmxlIDonLCBzeXMuZXhlY3V0YWJsZSk7IHByaW50KCdW
        echo ZXJzaW9uICAgIDonLCBzeXMudmVyc2lvbi5zcGxpdCgpWzBdKTsgcHJpbnQoJ1ByZWZpeCAgICAg
        echo OicsIHN5cy5wcmVmaXgpIg0KZWNoby4NCg0KZWNobyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0NCmVjaG8gIHBpcCB2ZXJzaW9uDQpl
        echo Y2hvIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLQ0KIiVQWSUiIC1tIHBpcCAtLXZlcnNpb24NCmVjaG8uDQoNCmVjaG8gLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tDQplY2hv
        echo ICBJbnN0YWxsZWQgUGFja2FnZXMNCmVjaG8gLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tDQoiJVBZJSIgLW0gcGlwIGxpc3QNCmVjaG8u
        echo DQoNCmVjaG8gLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tDQplY2hvICBEZXBlbmRlbmN5IEhlYWx0aA0KZWNobyAtLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0NCiIlUFklIiAt
        echo bSBwaXAgY2hlY2sNCmVjaG8uDQoNCmVjaG8gLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tDQplY2hvICBFbnRyeSBQb2ludCBDaGVjaw0K
        echo ZWNobyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0NCmlmIC9JICIlRU5UUllfTU9ERSUiPT0iZmlsZSIgKA0KICAgIGlmIGV4aXN0ICIl
        echo QVBQX0VOVFJZJSIgKA0KICAgICAgICBlY2hvIFtPS10gRW50cnkgZmlsZSBmb3VuZDogIiVBUFBf
        echo RU5UUlklIg0KICAgICkgZWxzZSAoDQogICAgICAgIGVjaG8gW0ZBSUxdIEVudHJ5IGZpbGUgTk9U
        echo IGZvdW5kOiAiJUFQUF9FTlRSWSUiDQogICAgKQ0KKSBlbHNlICgNCiAgICAiJVBZJSIgLWMgImlt
        echo cG9ydCBpbXBvcnRsaWIudXRpbCwgc3lzOyBuYW1lPXInJUFQUF9FTlRSWSUnOyBzcGVjPWltcG9y
        echo dGxpYi51dGlsLmZpbmRfc3BlYyhuYW1lKTsgcHJpbnQoKCdbT0tdIE1vZHVsZSBmb3VuZDogJyBp
        echo ZiBzcGVjIGVsc2UgJ1tGQUlMXSBNb2R1bGUgTk9UIGZvdW5kOiAnKSArIG5hbWUpOyBzeXMuZXhp
        echo dCgwIGlmIHNwZWMgZWxzZSAxKSIgMj5udWwNCiAgICBpZiBlcnJvcmxldmVsIDEgZWNobyBbRkFJ
        echo TF0gTW9kdWxlIGltcG9ydCB0ZXN0IGZhaWxlZC4NCiAgICBpZiAvSSAiJUVOVFJZX01PREUlIj09
        echo InJ1bm5lciIgZWNobyBbSU5GT10gUnVubmVyIGFyZ3M6ICIlUlVOTkVSX0FSR1MlIg0KKQ0KZWNo
        echo by4NCg0KZWNobyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0NCmVjaG8gIFByb2plY3QgRmlsZXMNCmVjaG8gLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tDQppZiBleGlzdCAi
        echo dXYubG9jayIgICAgICAgICAgZWNobyBbT0tdICAgdXYubG9jayBmb3VuZA0KaWYgZXhpc3QgInB5
        echo cHJvamVjdC50b21sIiAgIGVjaG8gW09LXSAgIHB5cHJvamVjdC50b21sIGZvdW5kDQppZiBleGlz
        echo dCAicmVxdWlyZW1lbnRzLnR4dCIgZWNobyBbT0tdICAgcmVxdWlyZW1lbnRzLnR4dCBmb3VuZA0K
        echo aWYgbm90IGV4aXN0ICJyZXF1aXJlbWVudHMudHh0IiBlY2hvIFtXQVJOXSByZXF1aXJlbWVudHMu
        echo dHh0IG1pc3NpbmcNCmVjaG8uDQoNCmVjaG8gLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tDQplY2hvICBQeVF0NiBXZWJFbmdpbmUgQ2hl
        echo Y2sNCmVjaG8gLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tDQoiJVBZJSIgLWMgImZyb20gUHlRdDYgaW1wb3J0IFF0Q29yZTsgcHJpbnQo
        echo J1B5UXQ6JywgUXRDb3JlLlBZUVRfVkVSU0lPTl9TVFIpOyBwcmludCgnUXQgIDonLCBRdENvcmUu
        echo UVRfVkVSU0lPTl9TVFIpOyBmcm9tIFB5UXQ2LlF0V2ViRW5naW5lV2lkZ2V0cyBpbXBvcnQgUVdl
        echo YkVuZ2luZVZpZXc7IHByaW50KCdbT0tdIFdlYkVuZ2luZSBpbXBvcnRlZCBzdWNjZXNzZnVsbHku
        echo JykiIDI+JjENCmlmIGVycm9ybGV2ZWwgMSAoDQogICAgZWNobyBbRkFJTF0gUHlRdDYgV2ViRW5n
        echo aW5lIGNoZWNrIGZhaWxlZC4NCiAgICBlY2hvICAgICAgICBSdW4gbWFudWFsbHkgZm9yIGZ1bGwg
        echo dHJhY2ViYWNrOg0KICAgIGVjaG8gICAgICAgICIlUFklIiAtYyAiZnJvbSBQeVF0Ni5RdFdlYkVu
        echo Z2luZVdpZGdldHMgaW1wb3J0IFFXZWJFbmdpbmVWaWV3Ig0KKSBlbHNlICgNCiAgICBlY2hvIFtP
        echo S10gUHlRdDYgV2ViRW5naW5lIGlzIGF2YWlsYWJsZS4NCikNCmVjaG8uDQoNCmVjaG8gPT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQpl
        echo Y2hvICBET0NUT1IgQ09NUExFVEUNCmVjaG8gPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQpwYXVzZQ0KZXhpdCAvYiAwDQo=
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

rem ── test.bat ─────────────────────────────────────────────────
set "OUTFILE=test.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_test_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpzZXRsb2NhbA0KY2QgL2QgIiV+ZHAwIg0KDQpyZW0gPT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQpyZW0gIFByb2pl
        echo Y3QgdGVzdCBydW5uZXINCnJlbSAgR2VuZXJhdGVkIGJ5IFZlbnYgQmF0Y2ggVGVtcGxhdGUgR2Vu
        echo ZXJhdG9yIChMZW9uIFByaWVzdCAvIDdoM3YwMWQpIHYzLjQuMA0KcmVtICBHZW5lcmF0ZWQgb246
        echo IDIwMjYtMDYtMjMgMTY6MjYNCnJlbQ0KcmVtICBSdW5zIHB5dGVzdCB2aWEgdGhlIHByb2plY3Qt
        echo bG9jYWwgdmVudiBQeXRob24uDQpyZW0NCnJlbSAgVXNhZ2U6DQpyZW0gICAgdGVzdC5iYXQgICAg
        echo ICAgICAgICAgICAgICAgICAgICAocnVuIGFsbCB0ZXN0cykNCnJlbSAgICB0ZXN0LmJhdCB0ZXN0
        echo cy90ZXN0X2NvcmUucHkgICAgIChydW4gYSBzcGVjaWZpYyBmaWxlKQ0KcmVtICAgIHRlc3QuYmF0
        echo IC1rIG1hcHBlciAgICAgICAgICAgICAgKGZpbHRlciBieSBuYW1lKQ0KcmVtICAgIHRlc3QuYmF0
        echo IC12IC0tdGI9c2hvcnQgICAgICAgICAgKHZlcmJvc2Ugd2l0aCBzaG9ydCB0cmFjZWJhY2tzKQ0K
        echo cmVtID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PQ0KDQpzZXQgIlBST0pFQ1RfTkFNRT1UaW1lQ3JhZnQiDQpzZXQgIlZFTlZfRElSPS52
        echo ZW52Ig0Kc2V0ICJQWT0lQ0QlXCVWRU5WX0RJUiVcU2NyaXB0c1xweXRob24uZXhlIg0KDQppZiBu
        echo b3QgZXhpc3QgIiVQWSUiICgNCiAgICBlY2hvIFtFUlJPUl0gTG9jYWwgdmVudiB3YXMgbm90IGZv
        echo dW5kOg0KICAgIGVjaG8gICAgICAgICAiJVBZJSINCiAgICBlY2hvLg0KICAgIHBhdXNlDQogICAg
        echo ZXhpdCAvYiAxDQopDQoNCnRpdGxlICIlUFJPSkVDVF9OQU1FJSAtIFRFU1QiDQplY2hvID09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQ0K
        echo ZWNobyAgVGVzdGluZzogIiVQUk9KRUNUX05BTUUlIg0KZWNobyAgUHl0aG9uIDogIiVQWSUiDQpl
        echo Y2hvID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PQ0KZWNoby4NCiIlUFklIiAtbSBweXRlc3QgLXYgJSoNCnNldCAiRVhJVENPREU9JUVS
        echo Uk9STEVWRUwlIg0KDQplY2hvLg0KZWNobyA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0NCmlmICIlRVhJVENPREUlIj09IjAiICgNCiAg
        echo ICBlY2hvICBURVNUUyBQQVNTRUQNCikgZWxzZSAoDQogICAgZWNobyAgVEVTVFMgRkFJTEVEICBe
        echo KGV4aXQgY29kZTogJUVYSVRDT0RFJV4pDQopDQplY2hvID09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQ0KcGF1c2UNCmV4aXQgL2IgJUVY
        echo SVRDT0RFJQ0K
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

echo.
echo ============================================================
echo  SETUP COMPLETE
echo.
echo  Companion scripts written (existing files were NOT overwritten).
echo  Add them to .gitignore to keep your repo tidy.
echo.
echo  Next steps:
echo    run.bat    - Launch %PROJECT_NAME%
echo    sync.bat   - Reinstall / update dependencies
echo    shell.bat  - Open activated venv shell
echo    doctor.bat - Environment health check
echo    pip.bat    - Project-local pip wrapper
echo    test.bat   - Run pytest suite
echo ============================================================
pause
exit /b 0
